emoji_movies = [
    {"emoji": "🦁👑", "movie_name": "The Lion King"},
    {"emoji": "🕵️‍♀️🔍💼", "movie_name": "The Silence of the Lambs"},
    {"emoji": "👑👩‍🦰👸", "movie_name": "Brave"},
    {"emoji": "🧙🔮", "movie_name": "Harry Potter"},
    {"emoji": "🦸‍♂️🕷️", "movie_name": "Spider-Man"},
    {"emoji": "👽🚲🌕", "movie_name": "E.T. the Extra-Terrestrial"},
    {"emoji": "🏎️🔥", "movie_name": "Fast and Furious"},
    {"emoji": "🦕🌴", "movie_name": "Jurassic Park"},
    {"emoji": "🤴👸🐸", "movie_name": "The Princess and the Frog"},
    {"emoji": "👦🐯🐒🐘🌴", "movie_name": "The Jungle Book"},
    {"emoji": "🦊🐺🐗", "movie_name": "The Fox and the Hound"},
    {"emoji": "🔫🍔🍟", "movie_name": "Pulp Fiction"},
    {"emoji": "👦🎈🎈🎈", "movie_name": "Up"},
    {"emoji": "👨‍👩‍👧‍👦🏠", "movie_name": "Home Alone"},
    {"emoji": "🦸‍♂️🛡️🔨", "movie_name": "Thor"},
    {"emoji": "🐻🐰🦊", "movie_name": "Zootopia"},
    {"emoji": "🤖🦹‍♂️🦸‍♂️", "movie_name": "The Avengers"},
    {"emoji": "👩‍🦱🌟💫", "movie_name": "Wonder Woman"},
    {"emoji": "🎭🎨🎬", "movie_name": "La La Land"},
    {"emoji": "👦🎒🎓", "movie_name": "Dead Poets Society"},
    {"emoji": "🐭🧀", "movie_name": "Tom and Jerry"},
    {"emoji": "🌃🦇🤵", "movie_name": "Batman"},
    {"emoji": "🔫🏙️", "movie_name": "Die Hard"},
    {"emoji": "👮‍♂️🚨🚔", "movie_name": "Police Academy"},
    {"emoji": "🌌👨‍🚀👩‍🚀", "movie_name": "Apollo 13"},
    {"emoji": "🧟‍♀️🧟‍♂️🧟", "movie_name": "Night of the Living Dead"},
    {"emoji": "🚗🐦", "movie_name": "Cars"},
    {"emoji": "🏝️📝🍾", "movie_name": "The Beach"},
    {"emoji": "🐒🗼", "movie_name": "King Kong"},
    {"emoji": "🦸‍♀️🦇", "movie_name": "Batwoman"},
    {"emoji": "🧛‍♂️🧟‍♀️", "movie_name": "Dracula"},
    {"emoji": "👸🎶", "movie_name": "The Princess and the Frog"},
    {"emoji": "🦁👑", "movie_name": "The Lion King"},
    {"emoji": "🐉🗡️", "movie_name": "How to Train Your Dragon"},
    {"emoji": "🤖🔫", "movie_name": "RoboCop"},
    {"emoji": "🕵️‍♂️🔎", "movie_name": "Sherlock Holmes"},
    {"emoji": "🎭🔪", "movie_name": "Scream"},
    {"emoji": "👨‍👦🔨", "movie_name": "The Shining"},
    {"emoji": "👮‍♂️👽", "movie_name": "Men in Black"},
    {"emoji": "🏰🐉", "movie_name": "The Hobbit"},
    {"emoji": "🐼🍥", "movie_name": "Kung Fu Panda"},
    {"emoji": "🚀🤠", "movie_name": "Toy Story"},
    {"emoji": "🤡🎈", "movie_name": "It"},
    {"emoji": "🧑‍🚀👨‍🚀👩‍🚀🪐", "movie_name": "Interstellar"},
    {"emoji": "👨‍🌾🌾🌻", "movie_name": "Field of Dreams"},
    {"emoji": "🏫🧑‍🏫🍎", "movie_name": "Dead Poets Society"},
    {"emoji": "🚶‍♂️🌲", "movie_name": "Into the Wild"},
    {"emoji": "👮‍♂️💰", "movie_name": "Heat"},
    {"emoji": "🧛‍♀️🐺", "movie_name": "Twilight"},
    {"emoji": "🏎️🏎️🏎️", "movie_name": "Fast and Furious"},
    {"emoji": "🎬🐎", "movie_name": "Horse Whisperer"},
    {"emoji": "🐉👦", "movie_name": "Pete's Dragon"},
    {"emoji": "🚀👨‍🚀👽", "movie_name": "Apollo 13"},
    {"emoji": "🐍🧙‍♂️🎓", "movie_name": "Harry Potter and the Chamber of Secrets"},
    {"emoji": "🌵🌟", "movie_name": "High Noon"},
    {"emoji": "🏚️👻", "movie_name": "The Haunting"},
    {"emoji": "🕵️‍♀️🕵️‍♂️🔍", "movie_name": "Sherlock Holmes"},
    {"emoji": "🐦🏍️", "movie_name": "The Motorcycle Diaries"},
    {"emoji": "🐕🌲", "movie_name": "White Fang"},
    {"emoji": "🔪🎭", "movie_name": "Scream"},
    {"emoji": "👽📼", "movie_name": "The X-Files"},
    {"emoji": "👨‍👦🎈", "movie_name": "Up"},
    {"emoji": "👶🍼🍽️", "movie_name": "Baby's Day Out"},
    {"emoji": "🌲🌲🐻", "movie_name": "Brother Bear"},
    {"emoji": "🕰️👴🔫", "movie_name": "The Old Man and the Gun"},
    {"emoji": "🚣‍♂️🌴", "movie_name": "The Blue Lagoon"},
    {"emoji": "🌺🏄‍♂️", "movie_name": "Blue Crush"},
    {"emoji": "🚶‍♂️💨", "movie_name": "Forrest Gump"},
    {"emoji": "🚀🌌", "movie_name": "Interstellar"},
    {"emoji": "🎂🎉", "movie_name": "Sixteen Candles"},
    {"emoji": "🌵🏜️🏜️", "movie_name": "Three Amigos"},
    {"emoji": "👩‍❤️‍💋‍👨💍", "movie_name": "The Proposal"},
    {"emoji": "🧔🕶️", "movie_name": "The Matrix"},
    {"emoji": "👩‍❤️‍👨🍕", "movie_name": "When Harry Met Sally"},
    {"emoji": "🦁🐒🦓", "movie_name": "The Lion King"},
    {"emoji": "🤖🤵", "movie_name": "RoboCop"},
    {"emoji": "🐅🎾", "movie_name": "Wimbledon"},
    {"emoji": "🌍🐒", "movie_name": "Planet of the Apes"},
    {"emoji": "🧟‍♂️💥", "movie_name": "Zombieland"},
    {"emoji": "🧊🐧", "movie_name": "Happy Feet"}
]
