name: Docker Build and Push

on:
  push:
    tags:
      - 'api-release-*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["${{ matrix.ref }}"]
    steps:
    - uses: actions/checkout@v2
    - name: Extract version from tag
      run: echo "::set-output name=version::${{ matrix.tag }}  " | awk -F '-' '{ print $3 }'
      id: extract_version
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag platput/filmemo:${{ steps.extract_version.outputs.version }}
        docker tag platput/filmemo:${{ steps.extract_version.outputs.version }} platput/filmemo:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: |
        docker push platput/filmemo:${{ steps.extract_version.outputs.version }}
        docker push platput/filmemo:latest
