name: UI Build and Deploy

on:
  push:
    tags:
      - 'ui-release-*.*.*'

env:
  AWS_REGION: ap-south-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET_NAME: ${{ vars.S3_BUKCET_NAME }}
  S3_BUCKET_PATH: /

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --acl public-read
          local_dir: dist
          s3_dir: ${{ env.S3_BUCKET_PATH }}
          aws_region: ${{ env.AWS_REGION }}
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          endpoint: s3.${{ env.AWS_REGION }}.amazonaws.com
          bucket: ${{ env.S3_BUCKET_NAME }}
